### ISSUE TITLE
Having issues installing this.

### ISSUE THREAD

**Issue by jsgerman75** [XanderStrike/WhatUI#10]
[jay@whiterim WhatUI]$ python -V
Python 2.7.11 :: Anaconda 2.4.1 (64-bit)
[jay@whiterim WhatUI]$ python WhatUI.py
Traceback (most recent call last):
File "WhatUI.py", line 9, in <module>
from lib.auth import requires_auth
File "/home/jay/WhatUI/lib/auth.py", line 5, in <module>
import lib.settings as settings
File "/home/jay/WhatUI/lib/settings.py", line 27
print ''"No DB found, creating..."'
^
SyntaxError: EOL while scanning string literal

**Comment by jsgerman75** [comment]
Fixed
